### PR TITLE
Add pip requirements.txt file

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:
This pull-request adds a requirements file to ease getting all the package dependencies for TXRRC_data_harvest

It install the dependencies run `pip install -r requirements.txt`

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

### CODE REVIEW

**Comment by mlbelobraydi** [comment]
Thank you for the contribution @dcslagel. We are really taking some leaps that I had not anticipated with your additions. Can you please describe the future maintenance if we go forward with a requirements file? When will we know it is out of date or requires updating?

I had to check and I'm not as up-to-date as the requirements listed, so I'm unsure what that does to the code.

Sorry for all the questions, this is what happens when someone just jumps in and starts coding without previous experience. -- Matt

**Comment by mlbelobraydi** [comment]
https://github.com/mlbelobraydi/TXRRC_data_harvest/issues/18

This issue is part of the attached larger issue

**Comment by dcslagel** [comment]
@mlbelobraydi,  Those are good questions.  


The requirements.txt is a standard python/pip file.  You see it in most python projects that are intended for development collaboration because it communicates the project's dependencies.  So I encourage adding one.  It will add periodic maintenance task to the project, when it needs to be updated.

If you agree, then we should do another iteration on this pull-request. The versions of the packages that you have been working with are the most authoritative version.  So the versions I had the packages pinned to in requirements.txt aren't the best.  I removed then in commit 718d643, so you could see that.  The main effect of running `pip install -r requirements.txt` with the 718d643 version is that pip will use the version of any of the packages that are already installed and get the most current version of any package it has to install.   If this version is accepted then we should also include the versions that you have been working with in the documentation (README.md or elsewhere) so that developers will be able to get the same versions.  

There are 2 other main options.  
1.  We could pin the packages to the versions you are using. 
2. We could pin the packages to the versions you are using-or-newer. This is done with syntax like `mypackage=>1.0`
 If you prefer either of these approaches, let me know the versions and I'll update this pull-request

In these cases, there would be times, when your environment is updated and then the requirement.txt should be updated and committed.


The full story of requirements.txt has lots more decision considerations, I have tried to keep it to the main ones for the current decision.  

These are good resources for a more in-depth discussion:
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
https://pip.pypa.io/en/stable/reference/pip_install/#pip-install-examples
https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers
https://martin-thoma.com/python-requirements/

**Comment by mlbelobraydi** [comment]
I went ahead and updated to what you had originally. I like the idea. Let's go for it. I'm close to pushing a new update for all the files, so we'll have to verify that I don't violate these requirements, but I believe it will be ok. 

Let's use the >= option with the current most up-to-date versions and we can work it out if anything should change.

**Comment by dcslagel** [comment]
Okay, I created a 3rd commit with the newer versions that were in the first commit and changed `==` to `>=`.  So the logic will be: install this specified version or newer.

**Comment by mlbelobraydi** [comment]
Committed. Thank you for your help with this.

**Pull request merged**
